language: node_js

node_js:
  - "6"
  - "8"

sudo: false

matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - if [ "$TEST_SUITE" == "lint" ]; then npm run lint; else npm run test:unit; fi

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TEST_SUITE" != "lint" ]]; then npm run coverage; npm run coverage-coveralls; npm run coverage-codeclimate; fi
