language: node_js

node_js:
  - "6"
  - "8"

sudo: false

matrix:
  include:
    - node_js: "6"
      env: TEST_SUITE=lint

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - if [ "$TEST_SUITE" == "lint" ]; then npm run lint; else npm run test:unit; fi

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == "6" && "$TEST_SUITE" != "lint" ]]; then npm run coverage; ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
